# Generated by Django 4.0.4 on 2022-07-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.TextField(choices=[('In Stock', 'Live'), ('Out of Stock', 'Out of Stock'), ('Pending', 'Pending')], default='In Stock'),
        ),
    ]
